### PR TITLE
Update dependencies to latest versions:

### PR DESCRIPTION
**Pull request by Trendy**
* Update libmediainfo to 19.07
* Update libzen to 0.4.37
* Update build to output asm.js compatible code instead of WASM (the default)

### CODE REVIEW

**Comment by Trendy** [comment]
Hi there, I was looking into using this library and found that the dependencies hadn't been updated in a while. I still need to do some testing, but the change is pretty straight forward, so I thought I would put in the PR in case you'd like to include the changes in your repository :smile:

**Comment by Trendy** [comment]
I tested the changes using your Github page, and it works. Although, there was an issue with the current implementation calculating a chunk size of 0 when it was finished and entering an infinite loop. I can provide a pull request to fix this issue as well, if you would like.

**Comment by buzz** [comment]
> I tested the changes using your Github page, and it works. Although, there was an issue with the current implementation calculating a chunk size of 0 when it was finished and entering an infinite loop. I can provide a pull request to fix this issue as well, if you would like.

:+1:  Thanks a bunch for the PR. And, yes, I'd be glad to merge the other fix.

**Comment by Trendy** [comment]
No problem! I can get the github page working correctly sometime today, I ran into one other issue with the template not updating (no idea why, could just be my local setup), and I'll throw up a PR for the changes.

**Comment by buzz** [comment]
> No problem! I can get the github page working correctly sometime today, I ran into one other issue with the template not updating (no idea why, could just be my local setup), and I'll throw up a PR for the changes.

Awesome! :)

**Comment by tomwilsn** [comment]
> I tested the changes using your Github page, and it works. Although, there was an issue with the current implementation calculating a chunk size of 0 when it was finished and entering an infinite loop. I can provide a pull request to fix this issue as well, if you would like.

Any word on this fix? Tried this version but my process chunks just goes into an infinite loop on some files.

**Comment by tomwilsonisobar** [comment]
@Trendy Bump?

**Pull request merged**
